<?php

namespace Tests\Controllers\Settings;

use App\Models\Vehicles\Car;
use App\Models\User;
use TestCase;

class CarsTest extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::findOrFail(1);
    }

    public function test_index_page()
    {

        $this->actingAs($this->user);

        $this->visit("/vehicles/cars")->assertResponseOk();

    }

    public function test_create_page()
    {

        $this->actingAs($this->user);

        $this->visit("/vehicles/cars/create");

        $this->assertResponseOk();

    }
    public function test_edit_page()
    {

        $this->actingAs($this->user);

        $car = Car::first();

        $this->visit("/vehicles/cars/$car->id/edit");

        $this->assertResponseOk();

    }
}