<?php

namespace Tests\Controllers\Manager;

use App\Models\User;
use TestCase;

class FuelTypesTest extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::findOrFail(1);
    }


    public function test_index_page()
    {

        $this->actingAs($this->user);

        $this->visit("/dictionaries/fuel_types")->assertResponseOk();

    }

}